### ISSUE TITLE
Paper Mario

### ISSUE THREAD

**Issue by noradninja** [Rinnegatamante/DaedalusX64-vitaGL-Compatibility#13]
# Game summary
Paper Mario
US
# Daedalus X64 summary
Version: v.0.1

# Issues
Game flickers very rapidly. It appears that BG layer in most scenes is flickering over the top of polygon layer. Some menu layers don't draw in game select. Some sprites don't draw correctly (Bowser's body during intro cutscenes) but work fine during battle scenes. Otherwise, game runs around 45-60FPS without sound and is playable.

**Comment by Rinnegatamante** [comment]
Flickering issue should be solved on nightlies, can you re-check the game and tell me if it can be considered Playable now despite the glitches?

**Comment by noradninja** [comment]
In the latest release, flickering no longer happens. There is no longer a BG layer though- it is drawing as black. I would consider it playable but slow- it mostly hovers in the 15-25FPS range. Menu and sprite issues remain but at least it is playable somewhat.

**Comment by noradninja** [comment]
Just an update with more testing- played through the first boss (King Goomba). Afterwards, you go to Toad Town- to advance you have to keep going right. 
![102B3A20-8FAD-4C2F-A2B6-054A50AF25F8](https://user-images.githubusercontent.com/6692990/81002039-9ea10980-8e16-11ea-8a71-3afaa0c0db83.jpeg)
At this location (The first section of Toad Town), you have to disable Dynarec to move to the next area or emulator drops to single digit FPS and hangs. 
![E3D1E599-6BBD-4C88-BA75-E18AAAAEDFA9](https://user-images.githubusercontent.com/6692990/81002043-9fd23680-8e16-11ea-9730-51ce3ab9fb0d.jpeg)
If you re-enable Dynarec, emulator slows to a crawl and eventually becomes unresponsive.

**Comment by noradninja** [comment]
Latest nightly with texture caching is now running 28-30 FPS (almost always 30) which is full speed for this game.

**Comment by noradninja** [comment]
To clarify-I’ve now played up to the third chapter. The only major issue aside from menu graphics and sprite issues in dark areas (Dry Dry Ruins, sewers in Toad Town)-
If you enter Toad Town with Dynarec enabled, the game slows to the point it hangs at a black screen. You have to disable it before you enter the town, at which point the FPS is 4. Once you leave you can reenable it, and the FPS goes back to 25-30FPS. Something about the town causes the emulation with Dynarec to lag.

**Comment by Ted-bissada** [comment]
I started this game and im only in the prologue but i have noticed that it seems every time mario jumps or stops/starts walking in the overworld the entire fragment cache is dumped, i dont know anything about emulation so i cant really say if this is normal behaviour

**Comment by noradninja** [comment]
Latest nightly (5/12/20) no longer lags in Toad Town, making the game quite playable. Biggest remaining issueS revolve around incorrect menu drawing and sprite drawing errors.

**Comment by ianmckinney** [comment]
Emulator crashes when starting a new game on 0.4 and July 6th Nightly.
https://user-images.githubusercontent.com/25875170/84470245-c5353a00-ac37-11ea-937d-7016e807821a.jpg

**Comment by yuyumaster** [comment]
The game doesn't work in any of the 3 versions (Jap, Usa & Eur) using the 0.4 release. In the first 2 versions, the game crashes right at the beginning of a new game, and the European one doesn't even let you start the game (it seems to take the Yes/No question as "No" every single time you try to play a new file), it doesn't matter whether you use File 1 or File 4.

![IMG_20200712_105609](https://user-images.githubusercontent.com/68182196/87242585-61688180-c42e-11ea-90b9-26374b6f2c9c.jpg)
_"Yes" is actually "Yesn't" here._

However, if you change the language to any of the other 3 available (French, German and Spanish), a strange save file (which you have not created before and has as name a lot of quavers) appears:

![IMG_20200712_110040_624](https://user-images.githubusercontent.com/68182196/87242681-39c5e900-c42f-11ea-9491-592f6ee40a9f.jpg)

It actually lets you go ingame, appearing somewhere randomly at the very first hours of the game (the forest at the left of Goombas' town, to be precise):

![IMG_20200712_110352](https://user-images.githubusercontent.com/68182196/87242745-bce73f00-c42f-11ea-9416-7a206efa8ffa.jpg)

The problem here: although you can explore the map, you can't even play properly because you have 0 hp and 0 fp and Goombario is not in your team, so when you enter a battle you die in just a few seconds:

![IMG_20200712_110424](https://user-images.githubusercontent.com/68182196/87242751-d1c3d280-c42f-11ea-9e98-6d76147f81ad.jpg)

![IMG_20200712_110427](https://user-images.githubusercontent.com/68182196/87242762-eb651a00-c42f-11ea-8c68-bb4ccf3377b7.jpg)

Really strange, you can try if you want to.

Overall performance is actually great, even though it seems to struggle when Mario jumps and when using the Dash (pressing "Z" while moving with a real controller, "L" on Vita). I also tried saving the game at the Save Block of Goombas' town but it doesn't seem to work.

I'd suggest changing the label of "Playable" to "Ingame -" or similar, because it is misleading, older versions of Daedalus did let you begin your adventure at least, and although some graphical issues have been corrected in the latest version you can't play the game properly, so I'd focus on trying to make the game playable first and then on the graphical issues, which are not that bad in the current version of the emulator.

Hope this all helps, I just created an account only because I love the work you guys are doing and I love this game. My knowledge is limited, but I'd like to contribute as much as possible so as to get things right with this emulator and to be able to play the classic N64 games we all love on our Vita. 

Cheers!

**Comment by yuyumaster** [comment]
Hi again. After some testing of Paper Mario, I found a way to play it properly using the 0.4 version. 

What I did was the following:
-Reinstalled version 0.1, which loads a new game without an issue (Important: USA version only; European ver. has the same issues as in 0.4). 
-Created a savestate right at the beginning of the new game (the scene of Luigi checking the mail). and copied it to my PC
-Reinstalled ver. 0.4 again
-Copied the savestate again to my Vita
-Loaded it from Daedalusx64 0.4 and... IT WORKS!

I've only played until when Goombario joins you and you're heading to Toad Town, but everything seems to work fine up to this point. 

![WhatsApp Image 2020-07-12 at 19 21 01](https://user-images.githubusercontent.com/68182196/87252994-b381c500-c477-11ea-875f-e8ce06b48b36.jpeg)

The minor issues I've encountered are:
-The game locks automatically at 70fps, which makes the game run faster than it should (60fps). I tried using the Frame Limit option, but then while the game runs as it should, the music slows down and pops a lot (both sync and async sound options behave exactly the same), so it's better to play at 70fps, although battles require faster timing skills (pressing "A" to cover from an attack or to attack more effectively, holding the joystick to charge the hammer, etc.).

![WhatsApp Image 2020-07-12 at 19 46 28](https://user-images.githubusercontent.com/68182196/87253068-710cb800-c478-11ea-841c-eedcfe850416.jpeg)

-Despite the emulator locks the game at 70fps, framerate is somewhat unstable in some parts (depending mostly on the quantity of sprites onscreen and size of the environment), noticeable at Goomba's Village, where it sways between 40-50 fps most of the time:

![WhatsApp Image 2020-07-12 at 19 52 37](https://user-images.githubusercontent.com/68182196/87253178-6141a380-c479-11ea-9427-d375f18874d0.jpeg)
_It seems to have something to do with Mario's movement though, since if you let the character standing still in this same area, it reaches 60-62fps._

-Some minor graphical issues, especially at the beginning, where the change in lightning in the Castle makes the characters sprites look as though they are negative, and most of Bowser's body doesn't show up properly before the battle (although it does during and after the battle):

![WhatsApp Image 2020-07-12 at 19 21 01 (1)](https://user-images.githubusercontent.com/68182196/87253086-a1545680-c478-11ea-9fd1-516b8e404400.jpeg)
_Before the battle._

![WhatsApp Image 2020-07-12 at 19 21 01 (2)](https://user-images.githubusercontent.com/68182196/87253098-b0d39f80-c478-11ea-857a-d138254b31ad.jpeg)
_After the battle. Here, the Star Rod sprite is simply displayed as a gray block._

-You can't save games as you would normally do on the original system: once you save and restart, there are no saved files. This also happened to me with Mario 64, don't know if I forgot to config something but I can only use savestates. This could be an issue for games like DK64, which is infamous for freezing after 10 hours of non-stop gaming.

Other than that, the game plays great mostly, and I'm really happy that this method worked.

I'm leaving here the savestate I created at the beginning of the game so that everyone can play and test it on 0.4 (I guess it will work with the latest nightly too). REMEMBER: Only USA rom. 

[Paper Mario Savestate (USA).zip](https://github.com/Rinnegatamante/DaedalusX64-vitaGL-Compatibility/files/4909095/Paper.Mario.Savestate.USA.zip)

In case anyone doesn't know how to do it: Extract the .ss0 file as it comes, copy it into the data/DaedalusX64/SaveStates/ folder on your Vita, load the game and once the Nintendo logo appears, load Save State 0. 
Hope you enjoy it! I'll keep on testing it, so if I encounter any major issue I'll let you know.

**Comment by Rinnegatamante** [comment]
I'll set back it to Playable then. For the wrong framerate limit, can you report your finding here? https://github.com/Rinnegatamante/DaedalusX64-vitaGL/issues/91

**Comment by XeroraYT** [comment]
Wanted to add an update to this. 

# Game summary
- Game name: Paper Mario
- Game version: USA

# Daedalus X64 summary
- Version: v0.6 with DynaRec

# Issues

Framerate hitching, graphical render bugs with menu's, full emulator crash to home screen when pause is pressed

# Screenshots
N/A - Similar to OP images

# Recommended labels

- C+/B-

**Comment by adrianbass360** [comment]
US VERSION PLAYABLE WITH MINOR GLITCHES. You can use this config and this specific daedalusx64 version:

[Configs.zip](https://github.com/user-attachments/files/19820100/Configs.zip)
[DaedalusX64 v0.6c (6de304)(09-17-23).zip](https://github.com/user-attachments/files/19820101/DaedalusX64.v0.6c.6de304.09-17-23.zip)

**Comment by 0lorak** [comment]
> Emulator crashes when starting a new game on 0.4 and July 6th Nightly. https://user-images.githubusercontent.com/25875170/84470245-c5353a00-ac37-11ea-937d-7016e807821a.jpg

Paper Mario mods as [Paper Mario: Star Nova](https://youtu.be/EOZQR3QEEM8) show a similar crash when starting a new game.
